[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_SUPABASE_URL = "https://eweoumauqncfdrqybyjz.supabase.co"
  VITE_SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3ZW91bWF1cW5jZmRycXlieWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2ODAxNjgsImV4cCI6MjA3MjI1NjE2OH0.pt_XspiK-ZjnegWpq0gnuGrLnBvk41i1ZWYhePMgwwc"